name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: The version to release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Publish to pypi
        uses: ./.github/actions/publish
        with:
          version: ${{ env.VERSION }}
          pypi_token: ${{ secrets.PYPI_TOKEN }}
          gpat_token: ${{ secrets.GPAT_TOKEN }}


